version: '3'
services:
    api-testpax-web:
        build: .
        container_name: api-testpax-web
        entrypoint:  dockerize -template ./.docker/app/.env.template:.env -wait tcp://db-api-testpax-web:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - DB_HOST=db-api-testpax-web
            - DB_PORT=3306
            - DB_DATABASE=api-testpax-web
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - APP_URL=http://localhost:8080
        volumes:
            - .:/var/www
        networks:
            - api-testpax-web-network
        depends_on:
            - db-api-testpax-web
            - redis-api-testpax-web

    nginx-api-testpax-web:
        build: .docker/nginx
        container_name: nginx-api-testpax-web
        restart: always
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        networks:
            - api-testpax-web-network
        depends_on:
            - api-testpax-web
    db-api-testpax-web:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db-api-testpax-web
        restart: always
        tty: true
        ports:
            - "3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=api-testpax-web
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - api-testpax-web-network

    redis-api-testpax-web:
        image: redis:alpine
        container_name: redis-api-testpax-web
        expose:
            - 6379
        networks:
            - api-testpax-web-network

networks:
    api-testpax-web-network:
        driver: bridge
